"use client"

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/auth/AuthProvider";
import Header from "@/components/Header";
import { ReactKeycloakProvider, useKeycloak } from "@react-keycloak/web";
import keycloak from "../../keycloak";
import { useEffect } from "react";
import AuthGuard from "@/auth/AuthGuard";
import Sidebar from "@/components/Sidebar";
import { usePathname } from "next/navigation";
import Dashboard from "./dashboard/page";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Taguig City WMS",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ReactKeycloakProvider authClient={keycloak}>
        <Header totalEarnings={10} />
          <AuthGuard>
            { children }
          </AuthGuard>
            
        </ReactKeycloakProvider>

      </body>
    </html>
    
  );
}
