apiVersion: v1
kind: Service
metadata:
  name: tcwms-fe
spec:
  selector:
    app: tcwms-fe
  ports:
    - protocol: TCP
      port: 3000  # External port
      targetPort: 3000  # Port your container is listening on
  type: LoadBalancer  # Change to "NodePort" if not using a cloud provider
